spring.docker.compose.enabled=true
spring.data.mongodb.uri=mongodb://superhero:superhero@localhost:27017/superheroes?authSource=admin
spring.data.mongodb.auto-index-creation=true

# Re-enable MongoDB auto-config, disable JPA/SQL
spring.autoconfigure.exclude=\
  org.springframework.boot.autoconfigure.orm.jpa.HibernateJpaAutoConfiguration,\
  org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
