spring.application.name=superheroes
spring.profiles.active=inmemory

spring.docker.compose.enabled=false

spring.autoconfigure.exclude=\
  org.springframework.boot.autoconfigure.data.mongo.MongoDataAutoConfiguration,\
  org.springframework.boot.autoconfigure.mongo.MongoAutoConfiguration

server.servlet.session.cookie.http-only=true
server.servlet.session.cookie.secure=false
server.servlet.session.cookie.same-site=lax
